// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentHub.Server.Data;

#nullable disable

namespace RentHub.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220109194618_AddExpenseToRoommate")]
    partial class AddExpenseToRoommate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("RentHub.Shared.Expenses.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePurchased")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoommateId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SplitCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoommateId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("RentHub.Shared.Roommate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyRentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roommates");
                });

            modelBuilder.Entity("RentHub.Shared.Expenses.Expense", b =>
                {
                    b.HasOne("RentHub.Shared.Roommate", null)
                        .WithMany("Expenses")
                        .HasForeignKey("RoommateId");
                });

            modelBuilder.Entity("RentHub.Shared.Roommate", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
